plugins {
    id 'java'
    id 'jacoco'
}

group = 'ru.nsu.vkuznetsov.task_1_1_2'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
    dependsOn test

    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    'ru/nsu/vkuznetsov/task_1_1_2/Main.class',
                    'ru/nsu/vkuznetsov/task_1_1_2/ui/**',
                    'ru/nsu/vkuznetsov/task_1_1_2/game/Round.class',
                    'ru/nsu/vkuznetsov/task_1_1_2/game/Game.class'
            ])
        }))
    }
}